//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPTLS {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPTLS.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App desenvolupada per adriapps.
        ///La imatge de &quot;Pedra&quot; Paper&quot; &quot;Tisora&quot; &quot;Llangardaix&quot; i &quot;Spock&quot; sota llicència Creative Commons a favor de Wikipedia..
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idioma1 {
            get {
                return ResourceManager.GetString("idioma1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canvia l&apos;idioma.
        /// </summary>
        public static string idioma2 {
            get {
                return ResourceManager.GetString("idioma2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llangardaix.
        /// </summary>
        public static string llangardaix {
            get {
                return ResourceManager.GetString("llangardaix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Llangardaix.
        ///Empat.
        /// </summary>
        public static string llangardaix_empat {
            get {
                return ResourceManager.GetString("llangardaix_empat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Llangardaix.
        ///Guanyes.
        /// </summary>
        public static string llangardaix_guanya {
            get {
                return ResourceManager.GetString("llangardaix_guanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Llangardaix.
        ///Perds.
        /// </summary>
        public static string llangardaix_perd {
            get {
                return ResourceManager.GetString("llangardaix_perd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador:
        ///Tu:
        ///Ordinador:.
        /// </summary>
        public static string marcador {
            get {
                return ResourceManager.GetString("marcador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper.
        /// </summary>
        public static string paper {
            get {
                return ResourceManager.GetString("paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Paper.
        ///Empat.
        /// </summary>
        public static string paper_empat {
            get {
                return ResourceManager.GetString("paper_empat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Paper.
        ///Guanyes.
        /// </summary>
        public static string paper_guanya {
            get {
                return ResourceManager.GetString("paper_guanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Paper.
        ///Perds.
        /// </summary>
        public static string paper_perd {
            get {
                return ResourceManager.GetString("paper_perd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedra.
        /// </summary>
        public static string pedra {
            get {
                return ResourceManager.GetString("pedra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Pedra.
        ///Empat.
        /// </summary>
        public static string pedra_empat {
            get {
                return ResourceManager.GetString("pedra_empat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Pedra.
        ///Guanyes.
        /// </summary>
        public static string pedra_guanya {
            get {
                return ResourceManager.GetString("pedra_guanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Pedra.
        ///Perds.
        /// </summary>
        public static string pedra_perd {
            get {
                return ResourceManager.GetString("pedra_perd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string resultat {
            get {
                return ResourceManager.GetString("resultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre....
        /// </summary>
        public static string sobre1 {
            get {
                return ResourceManager.GetString("sobre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre l&apos;applicació.
        /// </summary>
        public static string sobre2 {
            get {
                return ResourceManager.GetString("sobre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spock.
        /// </summary>
        public static string spock {
            get {
                return ResourceManager.GetString("spock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Spock.
        ///Empat.
        /// </summary>
        public static string spock_empat {
            get {
                return ResourceManager.GetString("spock_empat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Spock.
        ///Guanyes.
        /// </summary>
        public static string spock_guanya {
            get {
                return ResourceManager.GetString("spock_guanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Spock.
        ///Perds.
        /// </summary>
        public static string spock_perd {
            get {
                return ResourceManager.GetString("spock_perd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tisora.
        /// </summary>
        public static string tisora {
            get {
                return ResourceManager.GetString("tisora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Tisora.
        ///Empat.
        /// </summary>
        public static string tisora_empat {
            get {
                return ResourceManager.GetString("tisora_empat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Tisora.
        ///Guanyes.
        /// </summary>
        public static string tisora_guanya {
            get {
                return ResourceManager.GetString("tisora_guanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Màquina juga Tisora.
        ///Perds.
        /// </summary>
        public static string tisora_perd {
            get {
                return ResourceManager.GetString("tisora_perd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fes una jugada.
        /// </summary>
        public static string titol {
            get {
                return ResourceManager.GetString("titol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tornar.
        /// </summary>
        public static string tornar {
            get {
                return ResourceManager.GetString("tornar", resourceCulture);
            }
        }
    }
}
